### ISSUE TITLE
Numeração dos segmentos

### ISSUE THREAD

**Issue by fernandomr** [odoo-brazil/odoo-brazil-banking#21]
Numeração dos segmentos P e Q reinicia a cada line inclusa na rotina

self.arquivo.incluir_cobranca(**self._prepare_segmento(line))

Solucinado e validado com o banco Itaú no trecho a seguir, do @crsilveira
https://github.com/crsilveira/odoo-brazil-banking/commit/95d6476f1507058b1d38b7f9af69726f409cbf20

Procurei alterar a lib e o código Odoo para que não seja necessário retirar todo o código de dentro da lib e colocá-lo no módulo Odoo mas não obtive sucesso.

**Comment by mileo** [comment]
Postaram um issue sobre isso no cnab240?
